use crate::input::KeyCode;

impl std::fmt::Display for KeyCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            KeyCode::Unknown => "unknown",

            KeyCode::Backspace => "backspace",
            KeyCode::Tab => "tab",
            KeyCode::Enter => "enter",
            KeyCode::Escape => "escape",

            KeyCode::Space => "\' \'",
            KeyCode::Quote => "\''\'",
            KeyCode::Comma => "\',\'",
            KeyCode::Minus => "\'-\'",
            KeyCode::Period => "\'.\'",
            KeyCode::Slash => "\'/\'",

            KeyCode::_0 => "\'0\'",
            KeyCode::_1 => "\'1\'",
            KeyCode::_2 => "\'2\'",
            KeyCode::_3 => "\'3\'",
            KeyCode::_4 => "\'4\'",
            KeyCode::_5 => "\'5\'",
            KeyCode::_6 => "\'6\'",
            KeyCode::_7 => "\'7\'",
            KeyCode::_8 => "\'8\'",
            KeyCode::_9 => "\'9\'",

            KeyCode::SemiColon => "\';\'",
            KeyCode::Equals => "\'=\'",
            KeyCode::OpenBracket => "\'[\'",
            KeyCode::Backslash => "\'\\\'",
            KeyCode::CloseBracket => "\']\'",
            KeyCode::Tilde => "\'`\'",

            KeyCode::A => "\'a\'",
            KeyCode::B => "\'b\'",
            KeyCode::C => "\'c\'",
            KeyCode::D => "\'d\'",
            KeyCode::E => "\'e\'",
            KeyCode::F => "\'f\'",
            KeyCode::G => "\'g\'",
            KeyCode::H => "\'h\'",
            KeyCode::I => "\'i\'",
            KeyCode::J => "\'j\'",
            KeyCode::K => "\'k\'",
            KeyCode::L => "\'l\'",
            KeyCode::M => "\'m\'",
            KeyCode::N => "\'n\'",
            KeyCode::O => "\'o\'",
            KeyCode::P => "\'p\'",
            KeyCode::Q => "\'q\'",
            KeyCode::R => "\'r\'",
            KeyCode::S => "\'s\'",
            KeyCode::T => "\'t\'",
            KeyCode::U => "\'u\'",
            KeyCode::V => "\'v\'",
            KeyCode::W => "\'w\'",
            KeyCode::X => "\'x\'",
            KeyCode::Y => "\'y\'",
            KeyCode::Z => "\'z\'",

            KeyCode::LeftShift => "left shift",
            KeyCode::RightShift => "right shift",
            KeyCode::LeftControl => "left control",
            KeyCode::RightControl => "right control",
            KeyCode::LeftAlt => "left alt",
            KeyCode::RightAlt => "right alt",
            KeyCode::LeftSuper => "left super",
            KeyCode::RightSuper => "right super",

            KeyCode::Left => "left",
            KeyCode::Up => "up",
            KeyCode::Right => "right",
            KeyCode::Down => "down",

            KeyCode::F1 => "F1",
            KeyCode::F2 => "F2",
            KeyCode::F3 => "F3",
            KeyCode::F4 => "F4",
            KeyCode::F5 => "F5",
            KeyCode::F6 => "F6",
            KeyCode::F7 => "F7",
            KeyCode::F8 => "F8",
            KeyCode::F9 => "F9",
            KeyCode::F10 => "F10",
            KeyCode::F11 => "F11",
            KeyCode::F12 => "F12",

            KeyCode::CapsLock => "caps lock",
            KeyCode::ScrollLock => "scroll lock",
            KeyCode::NumLock => "num lock",

            KeyCode::PrintScreen => "print screen",
            KeyCode::Pause => "pause",
            KeyCode::Insert => "insert",
            KeyCode::Delete => "delete",
            KeyCode::Home => "home",
            KeyCode::End => "end",
            KeyCode::PageUp => "page up",
            KeyCode::PageDown => "page down",

            KeyCode::MediaPlayPause => "media play/pause",
            KeyCode::MediaStop => "media stop",
            KeyCode::MediaNextTrack => "media next track",
            KeyCode::MediaPreviousTrack => "media previous track",

            KeyCode::VolumeMute => "volume mute",
            KeyCode::VolumeDown => "volume down",
            KeyCode::VolumeUp => "volume up",

            KeyCode::Np0 => "numpad 0",
            KeyCode::Np1 => "numpad 1",
            KeyCode::Np2 => "numpad 2",
            KeyCode::Np3 => "numpad 3",
            KeyCode::Np4 => "numpad 4",
            KeyCode::Np5 => "numpad 5",
            KeyCode::Np6 => "numpad 6",
            KeyCode::Np7 => "numpad 7",
            KeyCode::Np8 => "numpad 8",
            KeyCode::Np9 => "numpad 9",
            KeyCode::NpDecimal => "numpad decimal",
            KeyCode::NpDivide => "numpad divide",
            KeyCode::NpMultiply => "numpad multiply",
            KeyCode::NpSubtract => "numpad subtract",
            KeyCode::NpAdd => "numpad add",
            KeyCode::NpEnter => "numpad enter",

            KeyCode::Menu => "menu",
        }
        .fmt(f)
    }
}
