mod display;

/// A key on the keyboard
#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[allow(missing_docs)]
pub enum KeyCode {
    Unknown = 0,

    Backspace = 8,
    Tab = 9,
    Enter = 13,
    Escape = 27,

    Space = b' ' as u16,
    Quote = b'\'' as u16,
    Comma = b',' as u16,
    Minus = b'-' as u16,
    Period = b'.' as u16,
    Slash = b'/' as u16,

    _0 = b'0' as u16,
    _1 = b'1' as u16,
    _2 = b'2' as u16,
    _3 = b'3' as u16,
    _4 = b'4' as u16,
    _5 = b'5' as u16,
    _6 = b'6' as u16,
    _7 = b'7' as u16,
    _8 = b'8' as u16,
    _9 = b'9' as u16,

    SemiColon = b';' as u16,
    Equals = b'=' as u16,
    OpenBracket = b'[' as u16,
    Backslash = b'\\' as u16,
    CloseBracket = b']' as u16,
    Tilde = b'`' as u16,

    A = b'a' as u16,
    B = b'b' as u16,
    C = b'c' as u16,
    D = b'd' as u16,
    E = b'e' as u16,
    F = b'f' as u16,
    G = b'g' as u16,
    H = b'h' as u16,
    I = b'i' as u16,
    J = b'j' as u16,
    K = b'k' as u16,
    L = b'l' as u16,
    M = b'm' as u16,
    N = b'n' as u16,
    O = b'o' as u16,
    P = b'p' as u16,
    Q = b'q' as u16,
    R = b'r' as u16,
    S = b's' as u16,
    T = b't' as u16,
    U = b'u' as u16,
    V = b'v' as u16,
    W = b'w' as u16,
    X = b'x' as u16,
    Y = b'y' as u16,
    Z = b'z' as u16,

    LeftShift = 128,
    RightShift,
    LeftControl,
    RightControl,
    LeftAlt,
    RightAlt,
    LeftSuper,
    RightSuper,

    Left,
    Up,
    Right,
    Down,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,

    CapsLock,
    ScrollLock,
    NumLock,

    PrintScreen,
    Pause,
    Insert,
    Delete,
    Home,
    End,
    PageUp,
    PageDown,

    MediaPlayPause,
    MediaStop,
    MediaNextTrack,
    MediaPreviousTrack,
    VolumeMute,
    VolumeDown,
    VolumeUp,

    Np0,
    Np1,
    Np2,
    Np3,
    Np4,
    Np5,
    Np6,
    Np7,
    Np8,
    Np9,
    NpDecimal,
    NpDivide,
    NpMultiply,
    NpSubtract,
    NpAdd,
    NpEnter,

    Menu,
}
